### ISSUE TITLE
Colors for JS and Typescript files are not like on Github

### ISSUE THREAD

**Issue by julien-c** [RealGithub/RealGithub-VSCode#5]
Hi, 

Tokenization of JS and TS files is not the same as on Github: see parameters and class attributes in attachment (Github on the left, VSCode on the right).

Thanks and keep up the good work!

![capture d ecran 2016-10-25 a 17 21 46](https://cloud.githubusercontent.com/assets/326577/19692322/c9dca27a-9ad7-11e6-996c-8db553b2f8c1.png)

**Comment by julien-c** [comment]
(I can send more examples if needed)

**Comment by julien-c** [comment]
Digging into it, I think this was broken by your latest release (worked well with the previous release)

![capture d ecran 2016-10-25 a 17 47 42](https://cloud.githubusercontent.com/assets/326577/19693280/3c280c36-9adb-11e6-986c-cb52d460093e.png)

**Comment by NoHomey** [comment]
@julien-c In fact i did changed the locals, parameters, and variables colors with `1.0.5` release due to [issue](https://github.com/RealGithub/RealGithub/issues/1) from @DavidStrada, but since there is no way to fix his exact issue (colors can not match on 100% githubs since there is difference in language support) I'll  just revert colors to what they were and merge your changes from #4  ...

**Comment by NoHomey** [comment]
@julien-c Unfortunally VSCode dose not support coloring `variable.parameter.{langauge}` scope for a given language only globally for the theme. But I opened [issue](https://github.com/Microsoft/vscode/issues/14536) at vscode. Making arguments orange for the whole theme would brake argumetnts colors for most themes:  examples are JavaScript, Ruby, Python, CoffeScript, Haskell.

**Comment by julien-c** [comment]
@NoHomey Cool! Thanks a lot. Your latest release looks much better than yesterday's already.

I also upvoted the issue you opened at `vscode`. Cheers 👍

**Comment by julien-c** [comment]
@NoHomey In case you haven't seen this yet (release notes for VSCode 1.7), this might help?

![img_0049](https://cloud.githubusercontent.com/assets/326577/20008697/dbaa68da-a2a1-11e6-93d6-304851f6d56a.PNG)

**Comment by NoHomey** [comment]
It seems the `1.7` release of VSCode fixed this issue (so I closed https://github.com/Microsoft/vscode/issues/14536). As well I've released new version of the theme with properly syntax highlighted function arguments.  Thanks for the issue @julien-c if you find other mismatches from the github theme, don't hasitate and open an issue I'll be more than happy to try fix it.

**Comment by julien-c** [comment]
Thanks for all the good work! The theme is still quite different from Github (lots of orange in the screenshot below for instance)

![capture d ecran 2016-11-07 a 19 09 33](https://cloud.githubusercontent.com/assets/326577/20069728/0f029b3e-a51e-11e6-98dc-4ffba43dbb70.png)
