### ISSUE TITLE
After update to Visual Studio Code 1.13 git notification colors are different

### ISSUE THREAD

**Issue by bojand** [RealGithub/RealGithub-VSCode#9]
Not sure if this is a Visual Studio Issue or theme issue but after the update to latest 1.13 version the git colors are different:

![image](https://user-images.githubusercontent.com/2081100/27097047-63bcac10-5049-11e7-8d2c-92e09cb900c4.png)

It was blue before. When using "Visual Studio Light" theme

![image](https://user-images.githubusercontent.com/2081100/27097296-26ec90a6-504a-11e7-9d90-d6b2e4ee5655.png)

**Comment by NoHomey** [comment]
I've also noticed the change ... But I'm currently in session in the university and I don't have time to "debug" it ... If you find what caused this issue just ping me and I'll fix it or you can submit a pull request.

**Comment by bojand** [comment]
NP. I will try and dig deeper. I also added an issue with VS Code as I had been able to reproduce with other themes.
